services:
  candlestick_repository:
    class: "domain/technicalAnalysis/CandlestickRepository"

  candlestick_collector:
    class: "domain/technicalAnalysis/CandlestickCollector"
    arguments:
      - "@exchange_builder"
      - "@candlestick_repository"

  candlestick_resolver:
    class: "domain/technicalAnalysis/CandlestickResolver"
    arguments:
      - "@candlestick_repository"
      - "@candlestick_collector"
