#!/usr/bin/env node

const solfege = require("solfegejs");
const Kryptopus = require("./src/Bundle");

const application = solfege.factory(`${__dirname}/config/config.yml`, [new Kryptopus()]);

application.start(process.argv.slice(2));
