#!/usr/bin/env node

const solfege = require("solfegejs");
const Kryptopus = require("./Bundle");

const application = solfege.factory();
application.addBundle(new Kryptopus());

application.start(process.argv.slice(2));
