version: "3.2"
services:
  btc:
    build: ./blockchain/btc
    ports:
      - "8332:8332"
    volumes:
      - type: volume
        source: btc_volume
        target: /root/.bitcoin
        volume:
          nocopy: true

volumes:
  btc_volume:
