services:
  wallet_balance:
    class: "command/WalletBalance"
    tags:
      - { name: "solfege.console.command" }

  mnemonic_random:
    class: "command/MnemonicRandom"
    tags:
      - { name: "solfege.console.command" }
