services:
    # Command to execute a bot
    kryptopus_bot_command_handler_execute:
        class: domain/bot/commandHandler/ExecuteBot
        arguments:
            - "@kryptopus_bot_builder"
            - "@kryptopus_bot_context_builder"

    # Query to list available bots
    kryptopus_bot_query_list:
        class: domain/bot/query/ListBots
        arguments:
            - "@kryptopus_bot_registry"


    # Register bots
    kryptopus_bot_registry:
        class: domain/bot/service/BotRegistry

    # Build bot instances
    kryptopus_bot_builder:
        class: domain/bot/service/BotBuilder
        arguments:
            - "@kryptopus_bot_registry"
            - "@container"

    # Service container dedicated to bots
    kryptopus_bot_container:
        class: "@container"

    # Build context for bots
    kryptopus_bot_context_builder:
        class: domain/bot/service/BotContextBuilder
        arguments:
            - "@kryptopus_bot_container"

