services:
    # Command handler to collect candles
    kryptopus_chart_command_handler_collect_candles:
        class: domain/chart/commandHandler/CollectCandles
        arguments:
            - "@kryptopus_chart_candle_collector_builder"

    # Register collector
    kryptopus_chart_candle_collector_registry:
        class: domain/chart/service/CandleCollectorRegistry

    # Build collector instances
    kryptopus_chart_candle_collector_builder:
        class: domain/chart/service/CandleCollectorBuilder
        arguments:
            - "@kryptopus_chart_candle_collector_registry"
            - "@container"


    # Register storage
    kryptopus_chart_candle_storage_registry:
        class: domain/chart/service/CandleStorageRegistry

    # Build storage instances
    kryptopus_chart_candle_storage_builder:
        class: domain/chart/service/CandleStorageBuilder
        arguments:
            - "@kryptopus_chart_candle_storage_registry"
            - "@container"


