services:
  collect_candlesticks_command:
    class: "application/cli/technicalAnalysis/CollectCandlesticks.command"
    arguments:
      - "@candlestick_collector"
    tags:
      - { name: "solfege.console.command" }

  check_candlesticks_command:
    class: "application/cli/technicalAnalysis/CheckCandlesticks.command"
    tags:
      - { name: "solfege.console.command" }

  display_candlestick_command:
    class: "application/cli/technicalAnalysis/DisplayCandlesticks.command"
    arguments:
      - "@candlestick_repository"
    tags:
      - { name: "solfege.console.command" }

  start_collector_daemon:
    class: "application/cli/technicalAnalysis/StartCollectorDaemon.command"
    tags:
      - { name: "solfege.console.command" }

  display_collector_daemon_status:
    class: "application/cli/technicalAnalysis/DisplayCollectorDaemonStatus.command"
    tags:
      - { name: "solfege.console.command" }

  stop_collector_daemon:
    class: "application/cli/technicalAnalysis/StopCollectorDaemon.command"
    tags:
      - { name: "solfege.console.command" }

  collector_daemon:
    class: "application/cli/technicalAnalysis/CollectorDaemon.command"
    arguments:
      - "%technicalAnalysis.candlestickCollector%"
      - "@candlestick_collector"
    tags:
      - { name: "solfege.console.command" }

  display_graph_candlestick_command:
    class: "application/cli/technicalAnalysis/DisplayGraphCandlesticks.command"
    arguments:
      - "@candlestick_resolver"
    tags:
      - { name: "solfege.console.command" }

  generate_graph_command:
    class: "application/cli/technicalAnalysis/GenerateGraph.command"
    arguments:
      - "@candlestick_resolver"
    tags:
      - { name: "solfege.console.command" }


