exchanges:
    my_bitstamp:
        type: bitstamp
        customer_id: abcd
        api_key: abcd
        api_secret: abcd

    my_binance:
        type: binance
        api_key: abcd
        api_secret: abcd

plugins:
    hello-world: file:examples/lib/bots/HelloWorld

