kryptopus:
    server: https://api.kryptopus.com/v1/
    api_key: abcd
    api_secret: abcd

exchanges:
    bitstamp:
        type: bitstamp
        customer_id: abcd
        api_key: abcd
        api_secret: abcd



