services:
  trading_position_creator:
    class: "%__dirname%/PositionCreator"
    arguments:
      - "@trading_position_repository"
    tags:
      - { name: "kryptopus.trading.service", id: "positionCreator" }

  trading_order_service:
    class: "%__dirname%/OrderService"
    tags:
      - { name: "kryptopus.trading.service", id: "order" }


